# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'com.jcadrg.BlocSpot2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for com.jcadrg.BlocSpot2
	pod 'SwiftIcons', '~> 2.0.1'
  target 'com.jcadrg.BlocSpot2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'com.jcadrg.BlocSpot2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
